#version: '3.8'

services:
  initdb:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # Cargar estructura inicial de BD
    networks:
      - mynetwork

  phishing-web:
    container_name: phishing-web
    build:
      context: ./phishing-web
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - initdb
    ports:
      - "5000:5000"
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./phishing-web:/usr/share/nginx/html
    networks:
      - mynetwork

  resultados-web:
    container_name: resultados-web
    build:
      context: ./resultados-web
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - initdb
      - php-fpm
    ports:
      - "5001:80"
    volumes:
      #- ./resultados-web/nginx.conf:/etc/nginx/nginx.conf
      - ./resultados-web:/var/www/html
    networks:
      - mynetwork

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./resultados-web:/var/www/html
    networks:
      - mynetwork

  nginx:
    container_name: proyecto-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./resultados-web:/var/www/html
      - ./phishing-web:/usr/share/nginx/html
    depends_on:
      - phishing-web
      - resultados-web
      - php-fpm
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

