version: '3.8'

services:
  initdb:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # Cargar estructura inicial de BD
    networks:
      - mynetwork

  phishing-web:
    container_name: phishing-web
    build: ./phishing-web  # Tu primer servidor Flask
    restart: always
    depends_on:
      - initdb
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  resultados-web:
    container_name: resultados-web
    build: ./resultados-web  # Otro servidor Flask si lo necesitas
    restart: always
    depends_on:
      - initdb
    ports:
      - "5001:5001"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
    - phishing-web
    - resultados-web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/phishing-web.conf:/etc/nginx/conf.d/phishing-web.conf
      - ./nginx/resultados-web.conf:/etc/nginx/conf.d/resultados-web.conf
    networks:
      - mynetwork

networks:
  mynetwork:
      
