version: '3.8'

services:
  initdb:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "proyectose@"
      MYSQL_DATABASE: "bd_keyloggers"
      MYSQL_USER: "sea"
      MYSQL_PASSWORD: "proyectose@"
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # Cargar estructura inicial de BD

  phishing-web:
    container_name: phishing-web
    build: ./phishing-web  # Tu primer servidor Flask
    restart: always
    depends_on:
      - initdb
    ports:
      - "5000:5000"

  resultados-web:
    container_name: resultados-web
    build: ./resultados-web  # Otro servidor Flask si lo necesitas
    restart: always
    depends_on:
      - initdb
    ports:
      - "5001:5001"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
    - phishing-web
    - resultados-web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
