FROM nginx:latest

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
#COPY resultados-web.conf /etc/nginx/conf.d/resultados-web.conf

# Exponer puerto 80
EXPOSE 5001
