FROM nginx:latest

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/nginx.conf
#COPY phishing-web.conf /etc/nginx/conf.d/phishing-web.conf

# Exponer puerto 80
EXPOSE 5000
